### ISSUE TITLE
Github repository와 Amplify web hosing 연동하여 자동배포하기

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#18]
아직은 Console을 통하여 저희 깃헙 리포지토리와 Amplify가 연동되는 것을 본 걸음마 단계이고,

`frontend/kendra-button-frontend` 폴더 안에서 빌드된 React 어플리케이션의 경로를 지정하여 호스팅된 Amplify의 url을 들어갔을 때 내용이 뜨게 하는 것이 목표

### 참고자료
- [Amplify Documentation: CLI: Hosting](https://docs.amplify.aws/cli/hosting#stages)
- [YouTube Tutorial: Hosting & Continuous Deployment for Front Ends and Serverless Back Ends using AWS Amplify](https://www.youtube.com/watch?v=SHBCim7IzG0)
- [YouTube Tutorial: Amplify Console Hosting - Manual Deploys from the Amplify CLI](https://www.youtube.com/watch?v=CBqXEx22oy4)
- [Configuring Build Settings](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#yml-specification-syntax)

**Comment by hunkim** [comment]
+1

**Comment by nalbam** [comment]
App settings > Rewrites and redirects 에서 다음을 설정 합니다.

Source address 
```
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|json|map)$)([^.]+$)/>
```

Target address: /index.html
Type: 200 (Rewrite)

**Comment by geoseong** [comment]
`feature-frontend-auth` 브랜치에다가 현재 작업중인데요,

next.js 프로젝트의 [static HTML export](https://nextjs.org/docs/advanced-features/static-html-export#how-to-use-it) 스크립트를 보완하고, 

Amplify Console에서 `Build Settings`와 `Rewrites and redirects` 설정을 만져 주어서 우선 [https://feature-frontend-auth.d394g1cx0v24y5.amplifyapp.com/](https://feature-frontend-auth.d394g1cx0v24y5.amplifyapp.com/) 에서 잘 뜨는 것 확인했습니다.

![스크린샷 2020-05-29 오후 5 13 06](https://user-images.githubusercontent.com/19166187/83237554-0eb16e00-a1d0-11ea-8264-933eddccf7e8.png)
![스크린샷 2020-05-29 오후 5 12 52](https://user-images.githubusercontent.com/19166187/83237562-107b3180-a1d0-11ea-8ef3-231537d00fe0.png)

인제 next.js typescript와 amplify framework의 맞지 않는 문제를 해결해 보겠습니다..ㅎ

별다른 의견이 없다면 이번 issue는 close 해보려 합니다

**Comment by geoseong** [comment]
`feature-frontend-auth` 브랜치에 index 페이지와 admin페이지 (Cognito 연동된 Amplify Auth UI)를 구현 해서 Amplify Web Hosting까지 성공적으로 세팅 완료.

**Build Setting**
```yml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend/kendra-button-front
        - yarn
    build:
      commands:
        - pwd
        - yarn build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /frontend/kendra-button-front/src/out
    files:
      - '**/*'
  cache:
    paths: []
```

**Rewrites and redirects**

Source address | Target address | Type | Country code
-- | -- | -- | --
https://kendra.fun | https://www.kendra.fun | 301 (Redirect - Permanent) | -
